services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./pgadmin_volume:/var/lib/pgadmin"
    ports:
      - "8080:80"
  ingest_data:
    build: 
      context: ingest_data
      dockerfile: Dockerfile
    command: [
      "--table_name","green_taxi_trips",
      "--url","https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz",
      "--mode", "green"
    ]
    depends_on:
      - pgdatabase
